server:
  port: 8081

spring:
  application:
    name: service-hi


  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///1810a?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: root
    password: 123456

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  config-locations: classpath:mybatis/config.xml
